[package]
name = "gloss_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gloss"
path = "src/main.rs"

[dependencies]
gloss_core = { path = "../gloss_core" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
camino = "1"
